#index:
#  path: /
#  controller: App\Controller\HomepageController::index



#admin
adminLogin:
  path: /admin
  controller: App\Controller\admin\AdminController::adminLogin

#client
homeClient:
  path: /{_locale}
  controller: App\Controller\client\pages\HomepageController::homeClient
  defaults:
    _locale: '%locale%'
    requirements:
      _locale: fr|en|en

loginClient:
  path: /{_locale}/incription
  controller: App\Controller\client\pages\HomepageController::loginClient

dashboardClient:
  path: /{_locale}/dashboard
  controller: App\Controller\client\pages\HomepageController::dashboardClient

#contact
contactClient:
  path: /{_locale}/contact
  controller: App\Controller\client\pages\HomepageController::contactClient

#search
searchClient:
  path: /{_locale}/search
  controller: App\Controller\client\pages\HomepageController::searchClient

#cart
cartClient:
  path: /{_locale}/cart
  controller: App\Controller\client\pages\HomepageController::cartClient

#category
categoryClient:
  path: /{_locale}/{category}
  controller: App\Controller\client\pages\category\CategoryController::categoryClient

#language
changeLocaleClient:
  path: /{locale}
  controller: App\Controller\client\language\LanguageController::changeLocaleClient


#Personnalisation
productClient:
  path: /{_locale}/{category}/{product}
  controller: App\Controller\ProductController::productClient

#Personnalisation
personnalisationClient:
  path: /{_locale}/{category}/{product}/personnalisation
  controller: App\Controller\PersonnalisationController::personnalisationClient
