#index:
#  path: /
#  controller: App\Controller\HomeController::index

home:
  path: /home
  controller: App\Controller\pages\HomeController::home

home_fallback:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /home
    permanent: true

connect:
  path: /home/connect
  controller: App\Controller\pages\HomeController::homeConnect

Dashboard:
  path: /{locale}/dashboard
  controller: App\Controller\pages\HomeController::Dashboard

changeLocale:
  path: /{locale}/{url}
  controller: App\Controller\pages\HomeController::changeLocale

