#index:
#  path: /
#  controller: App\Controller\HomeController::index

home:
  path: /
  controller: App\Controller\pages\HomeController::home

login:
  path: /incription
  controller: App\Controller\pages\HomeController::login

Dashboard:
  path: /dashboard
  controller: App\Controller\pages\HomeController::Dashboard

changeLocale:
  path: /{locale}/{url}
  controller: App\Controller\pages\HomeController::changeLocale

