#index:
#  path: /
#  controller: App\Controller\HomepageController::index

#admin
adminLogin:
  path: /admin
  controller: App\Controller\admin\AdminController::adminLogin

#client
homeClient:
  path: /
  controller: App\Controller\client\pages\HomepageController::homeClient

loginClient:
  path: /incription
  controller: App\Controller\client\pages\HomepageController::loginClient

dashboardClient:
  path: /dashboard
  controller: App\Controller\client\pages\HomepageController::dashboardClient

#contact
contactClient:
  path: /contact
  controller: App\Controller\client\pages\HomepageController::contactClient

#search
searchClient:
  path: /search
  controller: App\Controller\client\pages\HomepageController::searchClient

#cart
cartClient:
  path: /cart
  controller: App\Controller\client\pages\HomepageController::cartClient

#categorie
categorieClient:
  path: /{categorie}
  controller: App\Controller\client\pages\HomepageController::categorieClient

#language
changeLocaleClient:
  path: /{locale}/{url}
  controller: App\Controller\client\language\LanguageController::changeLocaleClient
