#index:
#  path: /
#  controller: App\Controller\HomepageController::index

dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index


#admin
adminLogin:
  path: /admin
  controller: App\Controller\admin\AdminController::adminLogin

#admin
adminAddCategory:
  path: /admin/category/add
  controller: App\Controller\admin\AdminController::adminLogin

#client
homeClient:
  path: /{_locale}
  controller: App\Controller\client\homepage\HomepageController::homeClient
  defaults:
    _locale: '%locale%'
    requirements:
      _locale: fr|en|en

#contact
contactClient:
  path: /{_locale}/contact
  controller: App\Controller\client\homepage\HomepageController::contactClient

#search
searchClient:
  path: /{_locale}/search
  controller: App\Controller\client\homepage\HomepageController::searchClient

#category
categoryClient:
  path: /{_locale}/{category}
  controller: App\Controller\client\category\CategoryController::categoryClient

#language
changeLocaleClient:
  path: /{locale}
  controller: App\Controller\client\language\LanguageController::changeLocaleClient


#Product
productClient:
  path: /{_locale}/{category}/{product}/{id}/{color}
  controller: App\Controller\client\product\ProductController::productClient

#Personnalisation
personnalisationCheckInfo:
  path: /{_locale}/{category}/{product}/{id}/{color}/personnalisation
  controller: App\Controller\client\personnalisation\PersonnalisationController::personnalisationCheckInfo

