#index:
#  path: /
#  controller: App\Controller\HomeController::index

#admin
adminLogin:
  path: /admin
  controller: App\Controller\admin\AdminController::adminLogin

#client
homeClient:
  path: /
  controller: App\Controller\client\HomeController::homeClient

loginClient:
  path: /incription
  controller: App\Controller\client\HomeController::loginClient

dashboardClient:
  path: /dashboard
  controller: App\Controller\client\HomeController::dashboardClient

changeLocaleClient:
  path: /{locale}/{url}
  controller: App\Controller\client\HomeController::changeLocaleClient

#search
searchClient:
  path: /search
  controller: App\Controller\client\HomeController::searchClient

#cart
cartClient:
  path: /cart
  controller: App\Controller\client\HomeController::cartClient

#categorie
categorieClient:
  path: /{categorie}
  controller: App\Controller\client\HomeController::categorieClient

